apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
  namespace: kubernetes-dashboard
spec:
  containers:
  - name: temp-container
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
